#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Single-command, reproducible bring-up of the FMD stack + Authentik SSO.
#
#   git clone … && cd FMD && ./up.sh
#
# Generates all secrets on first run, builds + starts every service, and
# auto-provisions the Authentik admin API token so user management works
# immediately. Clients never touch Authentik — you manage users from the app.
# Re-running is safe (idempotent).
# ---------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")"

log()  { printf '\033[36m▸ %s\033[0m\n' "$*"; }
die()  { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

command -v docker >/dev/null  || die "Docker is not installed."
command -v openssl >/dev/null || die "openssl is required (to generate secrets)."

# --- 1. Secrets — generate .env on first run (reproducible from a clean clone) -
if [ ! -f .env ]; then
  log "Generating .env with fresh secrets…"
  cat > .env <<EOF
# Auto-generated by up.sh — git-ignored. Keep private.
AUTHENTIK_SECRET_KEY=$(openssl rand -hex 50)
AUTHENTIK_PG_PASS=$(openssl rand -hex 24)
AUTHENTIK_BOOTSTRAP_PASSWORD=$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9')
AUTHENTIK_BOOTSTRAP_EMAIL=admin@example.com
AUTHENTIK_BOOTSTRAP_TOKEN=$(openssl rand -hex 32)
EOF
fi
set -a; . ./.env; set +a

# --- 2. Compose command — prefer v2 (no recreate quirk) -----------------------
if docker compose version >/dev/null 2>&1; then DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then DC="docker-compose"
else die "Docker Compose not found."; fi
log "Using: $DC"

# --- 3. Build + start everything ---------------------------------------------
log "Building images + starting services (first run pulls Authentik — be patient)…"
if ! $DC up -d --build; then
  # compose v1 + Docker 29 can fail to *recreate* volume-mounted services. Drop
  # the changed app services and recreate them (data lives in named volumes).
  log "Recreate hiccup (compose v1) — recreating app services individually…"
  for svc in web api authentik-server authentik-worker; do $DC rm -sf "$svc" >/dev/null 2>&1 || true; done
  $DC up -d --build
fi

# --- 4. Wait for health ------------------------------------------------------
wait_for() {
  local name="$1" url="$2" tries=0
  printf "  %-18s" "$name"
  until curl -fsS -o /dev/null "$url" 2>/dev/null; do
    tries=$((tries + 1)); [ "$tries" -gt 150 ] && { echo "timeout"; return 1; }
    printf "."; sleep 2
  done; echo " ready"
}
log "Waiting for services…"
wait_for "api"       "http://localhost:4000/api/_health" || true
wait_for "Authentik" "http://localhost:9000/application/o/fmd/.well-known/openid-configuration" || \
  die "Authentik didn't come up — check: $DC logs authentik-server"

# --- 5. Ensure the admin API token is usable ---------------------------------
# A fresh boot provisions it from AUTHENTIK_BOOTSTRAP_TOKEN automatically; if
# Authentik already existed without it, provision it now (same effect).
log "Verifying user-management token…"
if ! curl -fsS -o /dev/null -H "Authorization: Bearer ${AUTHENTIK_BOOTSTRAP_TOKEN}" \
     "http://localhost:9000/api/v3/core/users/" 2>/dev/null; then
  log "Provisioning token on the running Authentik…"
  AKSRV="$($DC ps -q authentik-server 2>/dev/null || true)"
  [ -z "$AKSRV" ] && AKSRV="$(docker ps --format '{{.Names}}' | grep authentik-server | head -1)"
  docker exec -i "$AKSRV" ak shell -c "
from authentik.core.models import Token, User
u = User.objects.get(username='akadmin')
Token.objects.update_or_create(identifier='fmd-api-token', defaults={'user': u, 'key': '${AUTHENTIK_BOOTSTRAP_TOKEN}', 'intent': 'api', 'expiring': False})
print('token ok')
" >/dev/null 2>&1 || log "  (couldn't auto-provision — it will self-provision on next Authentik restart)"
fi

# --- 6. Done -----------------------------------------------------------------
printf '\n\033[32m✅ FMD is up.\033[0m\n'
cat <<EOF
   App        →  http://localhost:5173
   API        →  http://localhost:4000

   Users      →  manage from the app (header 👤 Users, or a [User Management]
                 button) — already connected, no Authentik needed.

   Authentik admin (you only, optional)  →  http://localhost:9000
                 login: akadmin  /  ${AUTHENTIK_BOOTSTRAP_PASSWORD:-see .env}
EOF
