import React, { useContext } from 'react'
import { useSource, keysOf, pickField, isNum, SchemaContext, useRefresh, useRules } from '../../data.js'
import { fieldName } from '../../parser.js'
import { passes } from '../../fmd/rules.js'
import { evalArith, parseAggregate, splitEntityField, aggregate } from '../../fmd/expr.js'
import { formatValue, fieldDef, fieldType } from '../../fmd/format.js'
import { EditableCell, NewRow } from './inputs.jsx'
import { classify, Checklist, Empty } from './legacy.jsx'
import { FormButton } from './forms.jsx'

// Filter rows by a view's `? condition` (a named rule or inline expression).
export const filterRows = (rows, cond, rules) => (rows && cond ? rows.filter((r) => passes(cond, r, rules)) : rows)

// ---- structured widgets (nested FMD syntax: rows of (Name) cards) ----

// A (Name) widget card whose body is the indented [Viz] tag(s) beneath it.
// A card that holds ONLY buttons renders as a compact action bar (no big card
// chrome) so an "actions" group doesn't waste a full card of space.
export function WidgetCard({ node }) {
  const kind = classify(node.name)
  const onlyButtons = node.children.length > 0 && node.children.every((c) => c.type === 'Button')
  if (onlyButtons) {
    return (
      <div className="action-bar">
        {node.children.map((c, i) => <FormButton key={i} node={c} />)}
      </div>
    )
  }
  return (
    <div className="widget" data-kind={kind}>
      <div className="widget-head">
        <h3>{node.name}</h3>
      </div>
      <div className="widget-body">
        {node.children.map((c, i) => (
          c.type === 'Button' ? <FormButton key={i} node={c} /> : <Viz key={i} node={c} />
        ))}
      </div>
    </div>
  )
}

// Dispatch a [Viz] node to its visualization. Each pulls from node.source.
export function Viz({ node }) {
  if (!node || node.type !== 'Viz') return null
  switch (node.viz) {
    case 'table': return <VizTable node={node} />
    case 'counter': return <VizCounter node={node} />
    case 'checklist': return <VizChecklist node={node} />
    case 'slider': return <VizSlider node={node} />
    case 'board': return <VizBoard node={node} />
    case 'calendar': return <VizCalendar node={node} />
    default: return null
  }
}

// The labels generated by a viz's [Count]/[Slide] (and plural) children.
export const itemEntries = (node) =>
  node.children.filter((c) => c.type === 'Item').flatMap((c) => c.items)

// Declared field names for a source, from the [Data] model.
export function useFields(source) {
  const schema = useContext(SchemaContext)
  return schema?.[source]?.fields || null
}

// STRICT field-reference resolution. A reference must match a declared field
// name exactly (prefix stripped, case-insensitive). Returns { name, key, ok }.
// `ok` is false when the reference resolves to no declared field -> an "issue".
// When the source is undeclared (no model and no rows) we can't validate, so
// `ok` is true to avoid false positives.
export function resolveField(fields, rows, ref) {
  const name = fieldName(ref)
  if (!name) return { name: '', key: null, ok: false }
  const pool = fields && fields.length
    ? fields.map((f) => f.name)
    : (rows && rows.length ? keysOf(rows) : null)
  if (!pool) return { name, key: name, ok: true }
  const key = pool.find((k) => k.toLowerCase() === name.toLowerCase()) || null
  return { name, key, ok: !!key }
}

// Find the record whose `key` field matches `label` (exact, then contains).
export function matchRecord(rows, label, key) {
  if (!rows || !key) return null
  const l = label.toLowerCase()
  return rows.find((r) => String(r[key] ?? '').toLowerCase() === l)
    || rows.find((r) => String(r[key] ?? '').toLowerCase().includes(l))
    || null
}

// A table with optional CRUD interactivity, driven by the tag prefix
// (cTable/uTable/dTable, any combination). Mutations hit the backend, then
// refresh re-fetches the data so the table reflects the database.
function VizTable({ node }) {
  const rows = filterRows(useSource(node.source), node.filter, useRules())
  const fields = useFields(node.source)
  const refresh = useRefresh()
  if (!rows) return <Empty source={node.source} />

  const cols = node.spec
    ? node.spec.split(',').map((s) => resolveField(fields, rows, s)).filter((c) => c.name)
    : keysOf(rows).filter((k) => k !== '_id').map((k) => ({ name: k, key: k, ok: true }))

  const crud = node.crud || ''
  const canCreate = crud.includes('c')
  const canUpdate = crud.includes('u')
  const canDelete = crud.includes('d')
  const api = (path, opts) => fetch(`/api/${encodeURIComponent(node.source)}${path}`, opts).then(refresh)

  const patch = (row, key, value) =>
    api(`/${row._id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ [key]: value }) })
  const remove = (row) => api(`/${row._id}`, { method: 'DELETE' })

  return (
    <table className="viz-table">
      <thead>
        <tr>{cols.map((c, i) => <th key={i}>{c.name}</th>)}{canDelete && <th className="row-action" />}</tr>
      </thead>
      <tbody>
        {rows.map((r, ri) => (
          <tr key={r._id ?? ri}>
            {cols.map((c, ci) => {
              const def = fieldDef(fields, c.key)
              return (
                <td key={ci}>
                  {def?.rollup
                    ? <RollupCell parentRow={r} def={def} parentSource={node.source} type={def.type} />
                    : def?.calc
                      ? formatValue(evalArith(def.calc, r), def.type)
                      : canUpdate && r._id != null
                        ? <EditableCell value={r[c.key]} field={def} onCommit={(v) => patch(r, c.key, v)} />
                        : formatValue(r[c.key], fieldType(fields, c.key))}
                </td>
              )
            })}
            {canDelete && (
              <td className="row-action">
                {r._id != null && <button className="del-btn" title="Delete row" onClick={() => remove(r)}>×</button>}
              </td>
            )}
          </tr>
        ))}
        {canCreate && <NewRow source={node.source} cols={cols} fields={fields} extraCol={canDelete} onAdded={refresh} />}
      </tbody>
    </table>
  )
}

function VizCounter({ node }) {
  const rows = filterRows(useSource(node.source), node.filter, useRules())
  const fields = useFields(node.source)
  if (!rows) return <Empty source={node.source} />
  const labelKey = rows.length ? pickField(rows, [/title|name|label/i], () => true) : null
  const valueKey = rows.length ? pickField(rows, [/count|qty|quantity|number|total|value/i], (k, r) => isNum(r[0][k])) : null
  const sub = node.spec && rows.length ? resolveField(fields, rows, node.spec) : null
  return (
    <div className="stat-grid">
      {itemEntries(node).map((it, i) => (
        it.expr
          ? <AggregateStat key={i} label={it.label} expr={it.expr} />
          : <MatchedStat key={i} label={it.label} rec={matchRecord(rows, it.label, labelKey)} valueKey={valueKey} sub={sub} fields={fields} />
      ))}
    </div>
  )
}

// A counter item matched to a record by label (the original behavior).
function MatchedStat({ label, rec, valueKey, sub, fields }) {
  return (
    <div className="stat">
      <div className="stat-val">{rec ? formatValue(rec[valueKey], fieldType(fields, valueKey)) : '—'}</div>
      <div className="stat-label">{label}</div>
      {sub && sub.ok && rec && <div className="stat-sub">{formatValue(rec[sub.key], fieldType(fields, sub.key))}</div>}
    </div>
  )
}

// A counter item backed by a live aggregate: count/sum/avg/min/max(Entity ? cond).
function AggregateStat({ label, expr }) {
  const schema = useContext(SchemaContext)
  const rules = useRules()
  const agg = parseAggregate(expr)
  const resolved = agg ? splitEntityField(agg.ref, new Set(Object.keys(schema || {}))) : {}
  const rows = useSource(resolved.source)
  const filtered = agg ? (rows || []).filter((r) => passes(agg.filter, r, rules)) : []
  return (
    <div className="stat">
      <div className="stat-val">{agg ? aggregate(agg.fn, filtered, resolved.field) : '—'}</div>
      <div className="stat-label">{label}</div>
    </div>
  )
}

// A [Rollup] cell: aggregate a child entity's rows scoped to THIS parent row,
// via the child's link back to the parent (or the `via` field). Resolves child
// [Calc] fields before aggregating, and honors a `? filter`.
function RollupCell({ parentRow, def, parentSource, type }) {
  const schema = useContext(SchemaContext)
  const rules = useRules()
  const agg = parseAggregate(def.rollup)
  const resolved = agg ? splitEntityField(agg.ref, new Set(Object.keys(schema || {}))) : {}
  const childRows = useSource(resolved.source)
  if (!agg) return <>—</>
  const lc = (s) => String(s ?? '').toLowerCase()
  const childSchema = schema[resolved.source] || { fields: [] }
  const childLink = (agg.via && childSchema.fields.find((f) => lc(f.name) === lc(agg.via)))
    || childSchema.fields.find((f) => f.type === 'link' && f.options?.source === parentSource)
  let scoped = childRows || []
  if (childLink) scoped = scoped.filter((r) => lc(r[childLink.name]) === lc(parentRow[childLink.options?.field]))
  scoped = scoped.filter((r) => passes(agg.filter, r, rules))
  const childField = childSchema.fields.find((f) => lc(f.name) === lc(resolved.field))
  const rowsForAgg = childField?.calc
    ? scoped.map((r) => ({ ...r, [resolved.field]: evalArith(childField.calc, r) }))
    : scoped
  const blank = scoped.length === 0 && (agg.fn === 'avg' || agg.fn === 'min' || agg.fn === 'max')
  return <>{blank ? '—' : formatValue(aggregate(agg.fn, rowsForAgg, agg.fn === 'count' ? null : resolved.field), type)}</>
}

function VizChecklist({ node }) {
  const rows = filterRows(useSource(node.source), node.filter, useRules())
  const fields = useFields(node.source)
  if (!rows) return <Empty source={node.source} />
  const [labelRef, statusRef] = (node.spec || '').split('/').map((s) => s.trim())
  const label = resolveField(fields, rows, labelRef)
  const status = resolveField(fields, rows, statusRef)
  return <Checklist rows={rows} labelKey={label.key} statusKey={status.key} />
}

function parseSliderSpec(spec) {
  // "Category Spend / Cap" -> { label: Category, spent: Spend, cap: Cap }
  if (!spec) return {}
  const [left, right] = spec.split('/').map((s) => s.trim())
  const tokens = (left || '').split(/\s+/).filter(Boolean)
  if (tokens.length >= 2) return { label: tokens[0], spent: tokens[1], cap: right }
  return { spent: tokens[0], cap: right }
}

function VizSlider({ node }) {
  const rows = filterRows(useSource(node.source), node.filter, useRules())
  const fields = useFields(node.source)
  if (!rows) return <Empty source={node.source} />
  const { label, spent, cap } = parseSliderSpec(node.spec)
  const L = resolveField(fields, rows, label)
  const S = resolveField(fields, rows, spent)
  const C = resolveField(fields, rows, cap)
  const labelKey = L.key || pickField(rows, [/category|name|label|title/i], (k, r) => !isNum(r[0][k]))
  return (
    <div className="summary">
      {itemEntries(node).map(({ label: lbl }, i) => {
        const rec = matchRecord(rows, lbl, labelKey)
        const s = Number(rec?.[S.key] || 0)
        const c = Number(rec?.[C.key] || 0) || s || 1
        return (
          <div className="bar-row" key={i}>
            <span className="bar-label">{lbl}</span>
            <span className="bar-track"><span className="bar-fill" style={{ width: `${Math.min(100, (s / c) * 100)}%` }} /></span>
            <span className="bar-val">{formatValue(s, fieldType(fields, S.key) || 'currency')}</span>
          </div>
        )
      })}
    </div>
  )
}

// A kanban board grouped by a field: [Board -> WorkOrders] Status.
function VizBoard({ node }) {
  const rows = filterRows(useSource(node.source), node.filter, useRules())
  const fields = useFields(node.source)
  if (!rows) return <Empty source={node.source} />
  const groupDef = node.spec ? resolveField(fields, rows, node.spec) : null
  const groupKey = groupDef?.key || (rows[0] && keysOf(rows).find((k) => k !== '_id'))
  const labelKey = pickField(rows, [/title|name|label|ticket|order|customer/i], () => true)
  const declared = fieldDef(fields, groupKey)?.options?.values
  const distinct = [...new Set(rows.map((r) => String(r[groupKey] ?? '')).filter(Boolean))]
  const columns = declared && declared.length ? declared : distinct
  return (
    <div className="board">
      {columns.map((col, i) => {
        const cards = rows.filter((r) => String(r[groupKey] ?? '') === col)
        return (
          <div className="board-col" key={i}>
            <div className="board-col-head">{col}<span className="board-count">{cards.length}</span></div>
            {cards.map((r, ri) => <div className="board-card" key={ri}>{formatValue(r[labelKey], fieldType(fields, labelKey))}</div>)}
          </div>
        )
      })}
    </div>
  )
}

// A month calendar placing records on a date field: [Calendar -> Appointments] Date.
function VizCalendar({ node }) {
  const rows = filterRows(useSource(node.source), node.filter, useRules())
  const fields = useFields(node.source)
  if (!rows) return <Empty source={node.source} />
  const dateKey = (node.spec ? resolveField(fields, rows, node.spec) : {}).key
  const labelKey = pickField(rows, [/title|name|label|customer|activity|reason|service/i], () => true)
  const now = new Date()
  const year = now.getFullYear(), month = now.getMonth()
  const startDay = new Date(year, month, 1).getDay()
  const days = new Date(year, month + 1, 0).getDate()
  const byDay = {}
  rows.forEach((r) => { const d = String(r[dateKey] ?? '').slice(0, 10); if (d) (byDay[d] = byDay[d] || []).push(r) })
  const cells = [...Array(startDay).fill(null), ...Array.from({ length: days }, (_, i) => i + 1)]
  const key = (day) => `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`
  return (
    <div className="calendar">
      <div className="cal-title">{now.toLocaleString('en-US', { month: 'long', year: 'numeric' })}</div>
      <div className="cal-grid">
        {['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'].map((d) => <div className="cal-dow" key={d}>{d}</div>)}
        {cells.map((day, i) => (
          <div className={`cal-cell${day ? '' : ' empty'}`} key={i}>
            {day && <div className="cal-day">{day}</div>}
            {day && (byDay[key(day)] || []).slice(0, 3).map((r, ri) => (
              <div className="cal-event" key={ri}>{formatValue(r[labelKey], fieldType(fields, labelKey))}</div>
            ))}
          </div>
        ))}
      </div>
    </div>
  )
}
